language: node_js
node_js:
- stable
branches:
  only:
    - main
    - master
    - stable
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: goodakira7@gmail.com
  api_key:
    secure: FDFIXCZBdt3vW4EwH3/7HGSUedHenBA1Bz5dRz1BRVCo+dVtKr5h6KqbLdnmvTPa2q5yka1l6lc2QDdsJQZwIuhNq0wmBMCWeEUcSWis2h1FWI2ZI6e+Wl+pm59e5lQaPZ/wAWd3bLwp2LzlLIj90hwFmAksWGe6X6NMvv6aX8Sj3YVRqwANpc2ibI0GIuwfVbIX0rYbp3xjS7EyjHBucA3YSUCOR1yZX6EKDrpo+I0DG1BaeE9lDGr+xCT6Z5ht19dwKiDwOBPbT2L4sKM/0PEcvaNEo0qGh2+U8h+40+0TuIIS1SRousBdpVqmeSedWO/ILs3XKZvBK8mCDS9l3fW3nxVW1qKiyWE1w7r+v436IyIZVpMlI+JSUcnT8t2IpqBpP8Va3013M0vfSr/Andb9Mskt/QwN5Xf4WZGYRM1as/Mg1MZJknwbR3Wu9TbvxiQ0hB/s16wJnZAokNW7IjHDgbzFkwIMuPZ1583BcT/1c6rfUXYR5Z2N0GaoXtgjyk5YCVFasxWfYTj876YTDYqJTRAxIZwJK9YwHeqUlRs3nc+gezY8tQv+DPWaiXiXxSwfTzje8hqoh+sLWjrt4AqDukasp7Hpi8YJGL+XDCez7LP/N8wxSJs/a3mFLKEYwhL+BvsqLoY/27XTnOfM8suE9CfkT6H3Y/Qx9qR/PwE=
  on:
    tags: true
    repo: fukaoi/stellar-suite
    branch: main
  skip_cleanup: 'true'
