language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: goodakira7@gmail.com
  api_key:
      secure: KN0XRJUQsqhh1YFAnzGLmROk4eUuG+3u1h0v8+VqQbnFEfjS0ncfeGri0wGXQ0C9tiQqLrTLN+Mz00UYHcLnD8idtF2GjK2NsTvAz979bebTRVB+G+eUmLdgjSV+nHaQzDRIHAhDsNlxgzO+VKUOxqkwAcvEHC5D5TL+cLyuIq8UhS1LaErwLaU/aswaLRSyn1THtmyzUUyDZUiVy5SE+5ebjoIiDB9xvYHdTUMLg4GNX7gDNiEfuM5GT593h8BP0OzxH3Xk5U7CydacUBO7iqBT14powvFnQxKpXNlMnfSkXwtPPvRuWh6nAODZz5Hmb4wdEfb4DsU/aa1j62R1DzeVcBxouVUPRjG+RxHgVEcTAidmgmF2v3pilDWP3GD1cOwxxaUBHhPrUqRozmuuqn67s5IWPkkdksKc8DMqK2MZrAK+siOSlJ6/rH8QSxmYbi4CSCJQvK3oukVA2z87essklGeeVYRjLDpDa0tMfOwVXPwqhFtSVbHrfXapOaa5Yc8G6yLldshNHGedF4Ba3o92iJBDPicjES5AlXVCoWnoL0GBVya2xINVwFbjrg/tDCIRdpey91ExztT6J4SoWc6lKoTHNmq/PGObzwEoqCuK7GGZLMuwQ9pWQT9PgUTgy/9rrtUfS2pDa57ilfgRfE4/E2ei2945Q98CJltUEIc=
  on:
    tags: true
    repo: fukaoi/stellar-suite
    branch: main
  skip_cleanup: 'true'
